grails-app/domain/com/offside/Player.groovy
package com.offside
import org.apache.commons.codec.digest.DigestUtils
import org.apache.commons.lang.RandomStringUtils

class Player {

	String login
	String email
	String passwordHash

	Profile profile

	Date dateCreated // Grails automatically set this value with created timestamp
	Date lastUpdated // Grails automatically set this value with last update timestamp


	//FIXME: belongsTo implies delete in cascade
	static belongsTo=Tournament
	static hasMany=[teams:Team,tournaments:Tournament]

	static constraints = {
		login(blank:false,size: 4..12,unique:true)
		email(blank:false,email:true,unique:true)
		passwordHash(blank:false)
		profile(nullable: true)
	}

	static scaffold = true

	static mapping = { profile lazy:false }

	public void setPasswordToHash (String clearPassword) {
		this.passwordHash=DigestUtils.md5Hex(clearPassword)
	}
	
	public boolean checkPassword (String clearPassword) {
		if (this.passwordHash==null)
			return false
		return DigestUtils.md5Hex(clearPassword) == this.passwordHash
	}
	

	@Override
	public String toString() {
		return "Player [login=" + login + ", email=" + email + ", passwordHash=" + passwordHash + "]"
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((login == null) ? 0 : login.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Player)) {
			return false;
		}
		Player other = (Player) obj;
		if (login == null) {
			if (other.login != null) {
				return false;
			}
		} else if (!login.equalsIgnoreCase(other.login)) {
			return false;
		}
		return true;
	}


}

grails-app/controllers/com/offside/PlayerController.groovy
package com.offside;
import com.grailsinaction.LameSecurityFilters
import grails.validation.Validateable

@Validateable
class RegisterCommand {

	String login
	String email

	String password
	String confirmPassword

	static constraints = {
		importFrom Player

		password (blank:false, size: 6..12,password:true)
		confirmPassword (blank:false, password:true, validator: { value,pc ->
			return value == pc.password
		})
	}

	@Override
	public String toString() {
		return "RegisterCommand [login=" + login + ", email=" + email + ", password=" + password + ", confirmPassword=" + confirmPassword + "]"
	}

	public void trim(){
		if (this.login!=null) {
			this.login=this.login.trim()
		}
		if (this.email!=null) {
			this.email=this.email.trim()
		}
		if (this.password!=null) {
			this.password=this.password.trim()
		}
		if (this.confirmPassword!=null) {
			this.confirmPassword=this.confirmPassword.trim()
		}
	}
}



@Validateable
class ForgotPasswordCommand {

	String login
	String email
	String password
	String confirmPassword


	//same constraints as Player, but I can't use importFrom because of the unique constraint of each one
	static constraints = {
		login(blank:false,size: 4..12)
		email(blank:false,email:true)
		importFrom RegisterCommand, include: [
			"password",
			"confirmPassword"
		]
	}

	@Override
	public String toString() {
		return "ForgotPasswordCommand [login=" + login + ", email=" + email + ", password=" + password + ", confirmPassword="+ confirmPassword + "]";
	}

	public void trim(){
		if (this.login!=null) {
			this.login=this.login.trim()
		}
		if (this.email!=null) {
			this.email=this.email.trim()
		}
		if (this.password!=null) {
			this.password=this.password.trim()
		}
		if (this.confirmPassword!=null) {
			this.confirmPassword=this.confirmPassword.trim()
		}
	}
}

@Validateable
class LoginCommand {
	String login
	String password

	static constraints = { importFrom RegisterCommand }

	@Override
	public String toString() {
		return "LoginCommand [login=" + login + ", password=" + password + "]";
	}

	public void trim(){
		if (this.login!=null) {
			this.login=this.login.trim()
		}
		if (this.password!=null) {
			this.password=this.password.trim()
		}
	}
}



class PlayerController {

	//automatically injects postService into the controller
	def playerService


	def index() {

	}

	def login (LoginCommand loginCommand) {
		log.debug "Los params son ${params}"
		log.debug "El command es ${loginCommand}"

		if (loginCommand.login!=null) {
			try {
				//limpio espacios en blanco
				loginCommand.trim()
				def player = playerService.login(loginCommand)
				def securityFilters = new LameSecurityFilters()
				securityFilters.setAuthentication(session,player)
				redirect (uri: '/player/home')
			}
			catch (PlayerLoginException playerLoginException) {
				return [playerView: playerLoginException.loginCommand]
			}
		}
	}

	def register (RegisterCommand registerCommand) {
		log.debug "Los params son ${params}"
		log.debug "El command es ${registerCommand}"

		if (registerCommand.login!=null) {
			try {
				registerCommand.trim()
				def player=playerService.register(registerCommand)

				flash.OKMessage = message(code: "register.OK", args: [player.login])
				redirect (uri: '/')
			}
			catch (PlayerRegisterException playerRegisterException) {
				return [playerView: playerRegisterException.registerCommand]
			}
			catch (PlayerException playerException){
				return [playerView: playerException.player]
			}
		}
	}

	def forgotPassword (ForgotPasswordCommand forgotPasswordCommand) {

		log.debug "Los params son ${params}"
		log.debug "El command es ${forgotPasswordCommand}"

		if (forgotPasswordCommand.login!=null) {
			forgotPasswordCommand.trim()

			try {
				Player player = null
				switch ( params.forgotPasswordSelected ) {
					case "login":
						player=playerService.forgotPasswordByLogin(forgotPasswordCommand)
						break
					case "email":
						player=playerService.forgotPasswordByEmail(forgotPasswordCommand)
						break
				}
				flash.OKMessage = message(code: "forgotPassword.OK", args: [player.login])
				redirect (uri: '/')
			}
			catch (PlayerForgotPasswordException playerForgotPasswordException) {
				return [forgotPasswordView: playerForgotPasswordException.forgotPasswordCommand,forgotPasswordSelected: params.forgotPasswordSelected]
			}
		}
	}


	def home() {
	}


	def logout () {
		def login = session.player.login
		
		session.invalidate()
		flash.OKMessage = message(code: "player.logout.ok", args: [login])
		redirect (uri: '/')
	}
}

grails-app/controllers/com/offside/TournamentController.groovy
package com.offside

class TournamentController {

   def scaffold = Tournament
   
   
   def createTournament()
   {
	   if (Tournament.findAll().size()==0) 
		   {
			   def Tournament newTournament=new Tournament()
			   newTournament.name="TestTournament"
			   newTournament.description="TestTournamentDescription"
			   if( ! newTournament.save(flush: true)) {
				   newTournament.errors.each {
						 println it
					}
				 }
		   }
   }
   
   def list(Integer max)
   {
	   createTournament()
	   params.max = Math.min(max ?: 10, 100)
	   [tournamentInstanceList: Tournament.list(params), tournamentInstanceTotal: Tournament.count()]
   }
}

grails-app/views/player/forgotPassword.gsp
<html>
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta name="layout" content="main">
<title><g:message code="forgotPassword.tab.title" /></title>
</head>
<body id="body">
	<h1>
		<g:message code="forgotPassword.header" />
	</h1>
	<p>
		<g:message code="forgotPassword.description" />
	</p>

	<!-- Forgot password errors -->
	<g:hasErrors>
		<div id="errorsPane" style="background-color: red;">
			<g:renderErrors bean="${forgotPasswordView}" as="list" />
		</div>
	</g:hasErrors>

	<div id="forgotPasswordPane">
		<g:form name="loginForm" controller="player" action="forgotPassword">
			<div id="selectPane">
				<p>
					<g:if test="${forgotPasswordSelected == 'login' || forgotPasswordSelected == null}">
						<input type="radio" name="forgotPasswordSelected" value="login"
							checked="checked" />
						<g:textField name="login" value="${forgotPasswordView?.login}" />
					</g:if>
					<g:else>
						<input type="radio" name="forgotPasswordSelected" value="login" />
						<g:textField name="login" value="" />
					</g:else>

					<label for="login"><g:message
							code="forgotPassword.label.login" /></label>
				</p>
				<p>
					<g:if test="${forgotPasswordSelected == 'email'}">
						<input type="radio" name="forgotPasswordSelected" value="email"
							checked="checked" />
						<g:textField name="email" value="${forgotPasswordView?.email}" />
					</g:if>
					<g:else>
						<input type="radio" name="forgotPasswordSelected" value="email" />
						<g:textField name="email" value="" />
					</g:else>
					<label for="email"><g:message
							code="forgotPassword.label.email" /></label>

				</p>

			</div>
			<div id="newPasswordPane">
				<p>
					<label for="password"><g:message
							code="forgotPassword.label.newPassword" /></label>
					<g:passwordField name="password" />
				</p>
				<p>
					<label for="confirmPassword"><g:message
							code="forgotPassword.label.confirmNewPassword" /></label>
					<g:passwordField name="confirmPassword" />
				</p>
			</div>
			<div id="buttonPane">
				<g:submitButton name="forgotBtn" value="Forgot" />
			</div>
		</g:form>
	</div>
</body>
</html>

grails-app/views/player/home.gsp
<html>
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<meta name="layout" content="main" />
<title><g:message code="player.home.tab.title" /></title>
</head>
<body id="body">
	<g:if test="${session?.authenticated}">
		<h1>
			<g:message code="player.home.wellcome"
				args="${[session?.player?.login]}" />
		</h1>

		<div id="optionsPane">
			<div id="profilePane">
				<g:message code="player.home.options.profile" />
				<!-- 
				<g:link controller="player" action="profile">
					<g:message code="player.home.options.profile" />
				</g:link>
				-->
			</div>
			<div id="tournamentsPane">
				<g:message code="player.home.options.tournaments" />
				<!-- 
				<g:link controller="tournament" action="index">
					<g:message code="player.home.options.tournaments" />
				</g:link> 
				-->
			</div>
			<div id="logout">
				<g:link controller="player" action="logout">
					<g:message code="player.home.options.logout" />
				</g:link>
			</div>

		</div>
	</g:if>
</body>
</html>

grails-app/views/player/index.gsp
<html>
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta name="layout" content="main">
<title><g:message code="login.tab.title" /></title>
</head>
<body id="body">
	<h1>
		Player Index
	</h1>
</body>
</html>

grails-app/views/player/login.gsp
<html>
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta name="layout" content="main">
<title><g:message code="login.tab.title" /></title>
</head>
<body id="body">
	<h1>
		<g:message code="login.promo.game" />
	</h1>
	<p>
		<g:message code="login.desc.game" />
	</p>
	<div id="notificationsFlashPane">
		<g:if test="${flash.OKMessage}">
			<div id="notificationOKPane" style="background-color: lightgreen;">
				${flash.OKMessage}
			</div>
		</g:if>

		<g:if test="${flash.KOMessage}">
			<div id="notificationKOPane" style="background-color: red;">
				${flash.KOMessage}
			</div>
		</g:if>

		<g:if test="${flash.infoMessage}">
			<div id="notificationInfoPane" style="background-color: blue;">
				${flash.infoMessage}
			</div>
		</g:if>
	</div>

	<!-- Login errors -->
	<g:hasErrors>
		<div id="errorsPane" style="background-color: red;">
			<g:renderErrors bean="${playerView}" as="list" />
		</div>
	</g:hasErrors>

	<div id="loginPane">
		<g:form name="loginForm" controller="player" action="login">
			<div class="formField">
				<label for="login"><g:message
						code="login.form.label.login" /> </label>
				<g:textField name="login" value="${playerView?.login}" />
			</div>
			<div class="formField">
				<label for="password"><g:message
						code="login.form.label.password" /> </label>
				<g:passwordField name="password" />
			</div>
			<div class="formField">
				<g:submitButton name="loginBtn" value="Login" />
			</div>
		</g:form>
	</div>

	<div id="registerPane">
		<g:link controller="player" action="register">
			<g:message code="login.link.register" />
		</g:link>
	</div>
	<div id="forgotPane">
		<g:link controller="player" action="forgotPassword">
			<g:message code="login.link.forgot.password" />
		</g:link> 
	</div>


</body>
</html>

grails-app/views/player/register.gsp
<html>
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta name="layout" content="main">
<title><g:message code="register.tab.title" /></title>
</head>


<body id="body">
	<h1>
		<g:message code="register.page.header" />
	</h1>

	<p>
		<g:message code="register.page.desc" />
	</p>
	
	<g:hasErrors>
		<div id="errorsPane" style="background-color: red;">
			<g:renderErrors bean="${playerView}" as="list" />
		</div>
	</g:hasErrors>

	<div id="registerPane">
		<g:form controller="player" action="register" name="registerForm">
			<div class="formField">
				<label for="login"><g:message
						code="register.form.label.login" /></label>
				<g:textField name="login" value="${playerView?.login}" />
			</div>

			<div class="formField">
				<label for="email"><g:message
						code="register.form.label.email" /></label>
				<g:textField name="email" value="${playerView?.email}" />
			</div>
			<div class="formField">
				<label for="password"><g:message
						code="register.form.label.password" /></label>
				<g:passwordField name="password" />
			</div>
			<div class="formField">
				<label for="confirmPassword"><g:message
						code="register.form.label.confirmPassword" /></label>
				<g:passwordField name="confirmPassword" />
			</div>
			<g:submitButton class="formButton" name="register" value="Register" />
		</g:form>
	</div>
</body>
</html>